{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "mysql.auth.rootPassword is required" .Values.mysql.auth.rootPassword | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: {{ .Values.mysql.image }}
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
{{- end }}