{
 "title": "Coffee Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Http Requests Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status) (smart_coffee_http_requests_total{route=\"/coffee/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Coffee Request Rate / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(smart_coffee_http_requests_total{route=\"/coffee/\", method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency GET Coffee",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(smart_coffee_http_request_duration_seconds_bucket{route=\"/coffee/\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Coffee Request Rate / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(smart_coffee_http_requests_total{route=\"/coffee/\", method=\"PUT\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency PUT Coffee",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(smart_coffee_http_request_duration_seconds_bucket{route=\"/coffee/\", method=\"PUT\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coffee API Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"coffee-api\"} |= ``"
    }
   ]
  }
 ]
}