grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    size: 1Gi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
